language: node_js
sudo: false
dist: trusty
node_js:
- 7.4 # Latest
- 6.9 # LTS
- 0.10 # Earliest version supported
cache:
  directories:
  - $HOME/.npm
script: npm test -- --timeout 15000
after_success:
- cat coverage/lcov.info | ./node_modules/.bin/codecov
